[tool.poetry]
name = "bob"
version = "0.1.0"
description = ""
authors = ["Vadym Gryshchuk <vagr@di.ku.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
